name: autotests

on: push

jobs:

  ftrackertest:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test
        run: |
          go test -v ./...
